name: Notify Changes

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  notify-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v4

      - uses: actions/cache/restore@v4
        with:
          path: slots.db
          key: slots-db-${{ github.run_id }}
          restore-keys: slots-db-

      - run: uv run main.py notify changes
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

      - uses: actions/cache/save@v4
        if: always()
        with:
          path: slots.db
          key: slots-db-${{ github.run_id }}
